### ISSUE TITLE
Make it possible to autostart webcam

### ISSUE THREAD

**Issue by fredrikbaberg** [fredrikbaberg/hassio-addons#101]

**Comment by fredrikbaberg** [comment]
One option is to add the following to `config.yaml`:
```
events:
    enabled: true
    subscriptions:
    -   command: supervisorctl start mjpg-streamer
        enabled: true
        event: Startup
        type: system
```
